#include "SimplifyLife.C"
void DrawPerformComp(){
    gStyle->SetErrorX(0);
    gStyle->SetOptStat(0);
    TFile *fmb = new TFile("merged_AnapAumb.root","ReadOnly");
    TFile *fmbcen = new TFile("merged_AnapAumbcentral.root","ReadOnly");
    TFile *fhmand = new TFile("merged_AnapAumb.root","ReadOnly");
    TFile *fhmor = new TFile("merged_AnapAumb.root","ReadOnly");
    TFile *fhmsouth = new TFile("merged_AnapAumb.root","ReadOnly");
    TFile *fhmnorth = new TFile("merged_AnapAumb.root","ReadOnly");
    const int ncav = 1;
    TCanvas *c1[ncav];
    for(int i=0;i<ncav;i++){
        c1[i] = new TCanvas();
    }
    TString histoname = "hcentbbcs";//"hntracknmpc";
    TString varname = "bbcs";
    TString var = "bbc charge south";//"# of central tracks";
    bool xory = 0;
    TH2F* hbbcsbbcn_mb = (TH2F*)fmb->Get(Form("%s",histoname.Data()));
    TH2F* hbbcsbbcn_mbcen = (TH2F*)fmbcen->Get(Form("%s",histoname.Data()));
    TH2F* hbbcsbbcn_hmand = (TH2F*)fhmand->Get(Form("%s",histoname.Data()));
    TH2F* hbbcsbbcn_hmor = (TH2F*)fhmor->Get(Form("%s",histoname.Data()));
    TH2F* hbbcsbbcn_hmsouth = (TH2F*)fhmsouth->Get(Form("%s",histoname.Data()));
    TH2F* hbbcsbbcn_hmnorth = (TH2F*)fhmnorth->Get(Form("%s",histoname.Data()));
if(xory){
    TH1F* hbbc_mb = (TH1F*)hbbcsbbcn_mb->ProjectionX("hbbc_mb",0,-1);
    TH1F* hbbc_mbcen = (TH1F*)hbbcsbbcn_mbcen->ProjectionX("hbbc_mbcen",0,-1);
    TH1F* hbbc_hmand = (TH1F*)hbbcsbbcn_hmand->ProjectionX("hbbc_hmand",0,-1);
    TH1F* hbbc_hmor = (TH1F*)hbbcsbbcn_hmor->ProjectionX("hbbc_hmor",0,-1);
    TH1F* hbbc_hmsouth = (TH1F*)hbbcsbbcn_hmsouth->ProjectionX("hbbc_hmsouth",0,-1);
    TH1F* hbbc_hmnorth = (TH1F*)hbbcsbbcn_hmnorth->ProjectionX("hbbc_hmnorth",0,-1);
}
else{
    TH1F* hbbc_mb = (TH1F*)hbbcsbbcn_mb->ProjectionY("hbbc_mb",0,-1);
    TH1F* hbbc_mbcen = (TH1F*)hbbcsbbcn_mbcen->ProjectionY("hbbc_mbcen",0,-1);
    TH1F* hbbc_hmand = (TH1F*)hbbcsbbcn_hmand->ProjectionY("hbbc_hmand",0,-1);
    TH1F* hbbc_hmor = (TH1F*)hbbcsbbcn_hmor->ProjectionY("hbbc_hmor",0,-1);
    TH1F* hbbc_hmsouth = (TH1F*)hbbcsbbcn_hmsouth->ProjectionY("hbbc_hmsouth",0,-1);
    TH1F* hbbc_hmnorth = (TH1F*)hbbcsbbcn_hmnorth->ProjectionY("hbbc_hmnorth",0,-1);
}
    //hbbc_mb->GetXaxis()->SetLimits(0,300);
    //hbbc_mb->Rebin(3);
    //hbbc_mbcen->Rebin(10);
    //hbbc_hmand->Rebin(3);
    //hbbc_hmor->Rebin(3);
    //hbbc_hmsouth->Rebin(3);
    //hbbc_hmnorth->Rebin(3);
    TH1F *hbbc_mbcenScale = (TH1F*)hbbc_mbcen->Clone("hbbc_mbcenScale");
    hbbc_mbcenScale->Scale(1./40);
    //hbbc_hm->Scale(1./hbbc_hm->Integral());
    c1[0]->cd();
    c1[0]->SetLogy();
    hbbc_mb->Draw();
    SetTitle(*hbbc_mb,Form("%s",var.Data()),"# of events","");
    //SetTitle(*hbbc_mb,"nvtx layer 1","# of events","");
    SetXRange(*hbbc_mb,0,300);
    SetYRange(*hbbc_mb,1,5e8);
    SetXRange(*hbbc_mbcen,0,300);
    SetXRange(*hbbc_hmand,0,300);
    SetXRange(*hbbc_hmor,0,300);
    SetXRange(*hbbc_hmsouth,0,300);
    SetXRange(*hbbc_hmnorth,0,300);
    SetStyle(*hbbc_mb,0.6,1,20,0,0);
    SetStyle(*hbbc_mbcen,0.6,4,20,0,0);
    SetStyle(*hbbc_mbcenScale,0.6,2,27,0,0);
    SetStyle(*hbbc_hmand,0.6,2,20,0,0);
    SetStyle(*hbbc_hmor,0.6,4,34,0,0);
    SetStyle(*hbbc_hmsouth,0.6,6,29,0,0);
    SetStyle(*hbbc_hmnorth,0.6,7,32,0,0);
    TLegend *leg = new TLegend(0.5,0.70,0.8,0.85);
    leg->SetBorderSize(0);
    leg->SetFillColor(0);
    leg->SetTextSize(0.045);
    leg->AddEntry(hbbc_mb,"p+Au minbias","pl");
   // leg->AddEntry(hbbc_mb_scale,"p+Au minbias * 50","pl");
    leg->AddEntry(hbbc_mbcen,"p+Au bbc central","pl");
    leg->AddEntry(hbbc_mbcenScale,"p+Au bbc central *0.025","pl");
 //   leg->AddEntry(hbbc_hmand,"p+Au high-mult AND","pl");
 //   leg->AddEntry(hbbc_hmor,"p+Au high-mult OR","pl");
  //  leg->AddEntry(hbbc_hmsouth,"p+Au high-mult south","pl");
  //  leg->AddEntry(hbbc_hmnorth,"p+Au high-mult north","pl");
    leg->Draw("same");
    hbbc_mbcen->Draw("same");
    hbbc_mbcenScale->Draw("same");
    double top5 = 48;
    TLine *l = new TLine(top5,0,top5,6e7);
    l->SetLineStyle(2);
    l->Draw();
  //  hbbc_hmand->Draw("same");
  //  hbbc_hmor->Draw("same");
  //  hbbc_hmsouth->Draw("same");
  //  hbbc_hmnorth->Draw("same");
    TLatex t;
t.SetTextSize(0.04);
    t.SetNDC();
t.DrawLatex(0.13,0.2,Form("mb mean:%.2f",hbbc_mb->GetMean(1)));
t.DrawLatex(0.13,0.25,Form("central mean:%.2f",hbbc_mbcen->GetMean(1)));
t.SetNDC(0);
t.DrawLatex(top5-20,1e8,Form("Top 0-5%, bbc charge >= %.1f",top5));
cout<<hbbcsbbcn_mb->GetEntries()<<endl;
cout<<hbbcsbbcn_mbcen->GetEntries()<<endl;
//t.DrawLatex(0.13,0.2,Form("mb mean:%.2f, # of events: %.1fM",hbbc_mb->GetMean(1),hbbcsbbcn_mb->Integral()/1e6));
//t.DrawLatex(0.13,0.25,Form("central mean:%.2f, # of events: %.1fM",hbbc_mbcen->GetMean(1),hbbcsbbcn_mbcen->Integral()/1e6));
//t.DrawLatex(0.13,0.80,Form("hm AND mean:%.2f, # of events: %.1fM",hbbc_hmand->GetMean(1),hbbcsbbcn_hmand->Integral()/1e6));
//t.DrawLatex(0.13,0.85,Form("hm OR mean:%.2f, # of events: %.1fM",hbbc_hmor->GetMean(1),hbbcsbbcn_hmor->Integral()/1e6));
//t.DrawLatex(0.13,0.90,Form("hm south mean:%.2f, # of events: %.1fM",hbbc_hmsouth->GetMean(1),hbbcsbbcn_hmsouth->Integral()/1e6));
//t.DrawLatex(0.13,0.95,Form("hm north mean:%.2f, # of events: %.1fM",hbbc_hmnorth->GetMean(1),hbbcsbbcn_hmnorth->Integral()/1e6));
    c1[0]->Print(Form("fig/h%s_comp.png",varname.Data()));
/*
    c1[1]->cd();
    TH1F* hbbc_ratiocen = (TH1F*)hbbc_mbcen->Clone("hbbc_ratiocen");
    TH1F* hbbc_ratioand = (TH1F*)hbbc_hmand->Clone("hbbc_ratioand");
    TH1F* hbbc_ratioand = (TH1F*)hbbc_hmand->Clone("hbbc_ratioand");
    TH1F* hbbc_ratioor = (TH1F*)hbbc_hmor->Clone("hbbc_ratioor");
    TH1F* hbbc_ratiosouth = (TH1F*)hbbc_hmsouth->Clone("hbbc_ratiosouth");
    TH1F* hbbc_rationorth = (TH1F*)hbbc_hmnorth->Clone("hbbc_rationorth");
    hbbc_ratiocen->Divide(hbbc_mb);
    hbbc_ratioand->Divide(hbbc_mb);
    hbbc_ratioor->Divide(hbbc_mb);
    hbbc_ratiosouth->Divide(hbbc_mb);
    hbbc_rationorth->Divide(hbbc_mb);
    SetTitle(*hbbc_ratioand,Form("%s",var.Data()),"ratio hm/mb","");
    //SetTitle(*hbbc_ratio,"nvtx layer 1","# of events","");
    SetXRange(*hbbc_ratioand,0,30);
    SetYRange(*hbbc_ratioand,0,1e2);
    hbbc_ratioand->Draw();
    hbbc_ratiocen->Draw();
    hbbc_ratioor->Draw("same");
    hbbc_ratiosouth->Draw("same");
    hbbc_rationorth->Draw("same");
    c1[1]->Print(Form("fig/h%s_ratio.png",varname.Data()));
*/
    /*
TH1F* hnvtx = (TH1F*)hbbcnvtx[0]->ProjectionX("hnvtx",0,-1);
TH1F* hnvtx_hm = (TH1F*)hbbcnvtx_hm[0]->ProjectionX("hnvtx_hm",0,-1);
TH1F* hbbc = (TH1F*)hbbcnvtx[0]->ProjectionX("hbbc",0,-1);
TH1F* hbbc_hm = (TH1F*)hbbcnvtx_hm[0]->ProjectionX("hbbc_hm",0,-1);
c1[22]->cd();
c1[22]->SetLogy();
hnvtx->Rebin(4);
hnvtx_hm->Rebin(4);
hnvtx->Scale(1./hnvtx->Integral());
hnvtx_hm->Scale(1./hnvtx_hm->Integral());
SetRange(*hnvtx,0,1e-11,200,10);
SetTitle(*hnvtx,"#hits in cluster layer 1","normalized","");
SetStyle(*hnvtx,1.2,1,20,0,0);
SetStyle(*hnvtx_hm,1.2,2,24,0,0);
hnvtx->Draw("P");
hnvtx_hm->Draw("Psame");
c1[22]->Print("fig/hnvtx.png");
c1[23]->cd();
c1[23]->SetLogy();
SetTitle(*hbbc,"bbc charge sum","normalized","");
hbbc->Rebin(5);
hbbc_hm->Rebin(5);
hbbc->Scale(1./hbbc->Integral());
hbbc_hm->Scale(1./hbbc_hm->Integral());
SetRange(*hbbc,0,1e-11,200,10);
SetStyle(*hbbc,1.2,1,20,0,0);
SetStyle(*hbbc_hm,1.2,2,24,0,0);
hbbc->Draw("P");
hbbc_hm->Draw("Psame");
c1[23]->Print("fig/hbbc.png");
*/


}
